name: Email Notification

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3.12.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: tirzahpeniche@gmail.com
        password: KimSeokJin
        subject: 'Changes pushed to branch ${{ github.ref }}'
        body: 'Changes have been pushed to branch ${{ github.ref }}'
        to: 'tirzahpeniche@gmail.com'
        from: Tirzah y Ferdi