name: Emain Notification

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Send Email Notification
      uses: send-email-action@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Changes pushed to branch ${{ github.ref }}'
        body: 'Changes have been pushed to branch ${{ github.ref }}'
        to: 'tirzahpeniche@gmail.com'